server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/amigo1975123123/microsevices-data-project
          search-paths: config-data
          username: ${USERNAME}
          password: ${TOKEN}
  application:
    name: config-service
