server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/GiuseppeCavallieri/ev2/tree/main/backend
          search-paths: config-data
  application:
    name: config-service
