server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/user/**
        - id: ms-rate
          uri: lb://ms-rate
          predicates:
            - Path=/rate/**
        - id: ms-specialrate
          uri: lb://ms-specialrate
          predicates:
            - Path=/specialrate/**
        - id: ms-discountnum
          uri: lb://ms-discountnum
          predicates:
            - Path=/discountnum/**
        - id: ms-discountfreq
          uri: lb://ms-discountfreq
          predicates:
            - Path=/discountfreq/**
        - id: ms-reservation
          uri: lb://ms-reservation
          predicates:
            - Path=/reservation/**
        - id: ms-rack
          uri: lb://ms-rack
          predicates:
            - Path=/rack/**