apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server-deployment
  labels:
    app: frontend-server-deployment
spec:
  selector:
    matchLabels:
      app: frontend-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-server-deployment
    spec:
      containers:
        - name: frontend-server-container
          image: giuseppe6/frontend:latest
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-server-deployment-service
  labels:
    app: frontend-server-deployment
spec:
  selector:
    app: frontend-server-deployment
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer